import Header from "@/components/Header/Header";
import "./globals.css";
import Footer from "@/components/Footer/Footer";

import Head from "next/head";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

      <html lang="en">
        <Head>
          <meta
            name="viewport"
            content="width=425, initial-scale=1.0, maximum-scale=1.0,user-scalable=1"
          />
        </Head>
        <body>
          <div className="container">
            <Header />
            {children}
            <Footer />
          </div>
        </body>
      </html>

  );
}
